apiVersion: v1
kind: PersistentVolume
metadata:
  name: chi-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/logs/
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: kube-system
  name: chi-kube-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/logs/
    type: DirectoryOrCreate